version: '3.8'

services:
  simplementinon:
    build: .
    container_name: simplementinon
    restart: always
    env_file:
      - .env
    environment:
      MONGO_URL: "mongodb://mongodb:27017"  
    ports:
      - "8000:8000"  
    depends_on:
      - mongodb
      

  mongodb:
    image: mongo:latest  
    container_name: mongodb

    restart: always
    ports:
      - "27017:27017"  
    volumes:
      - mongo_data:/data/db 



volumes:
  mongo_data: 
